---
- name: install dependency packages
  apt:
    name: apt-transport-https
- name: add gpg key
  apt_key:
    url: "https://mackerel.io/assets/files/GPG-KEY-mackerel"
- name: add repository
  apt_repository:
    repo: "deb http://apt.mackerel.io/debian/ mackerel contrib"
    filename: mackerel
- name: install mackerel-agent
  yum:
    name: mackerel-agent
- name: install mackerel-agent-plugins
  yum:
    name: mackerel-check-plugins
  when: mackerel_agent_install_agent_plugins
- name: install mackerel-check-plugins
  yum:
    name: mackerel-check-plugins
  when: mackerel_agent_install_check_plugins
- name: create mackerel-agent setting file
  template:
    src: mackerel-agent.conf.j2
    dest: /etc/mackerel-agent/mackerel-agent.conf
  notify: restart mackerel-agent
- name: mackerel-agent is active and enabled on system startup
  service:
    name: mackerel-agent
    state: started
    enabled: yes
  when: mackerel_agent_start_on_setup
